INSERT INTO EXPEDITION (ID , ETAT , ID_COMMANDE ) VALUES (1, 1, 1);
INSERT INTO EXPEDITION (ID , ETAT , ID_COMMANDE ) VALUES (2, 2, 3);
INSERT INTO EXPEDITION (ID , ETAT , ID_COMMANDE ) VALUES (3, 0, 2);
